:hyla: https://github.com/cmoulliard/hyla

= Instructions

== Generate slideshow and hands-on-labs

=== Prerequisites

- https://www.ruby-lang.org/en/[Ruby]
- http://guides.rubygems.org/[RubyGems] to install Ruby Applications

=== Install Hyla

You need {hyla}[Hyla] to generate the slideshow and hands-on-lab from the asciidoc files. 

The latest source code is located in the {hyla}[Hyla git repository] on GitHub. Hyla can be installed via the +gem+ command, bundler.

Use `gem install` command to install Hyla :

    $ gem install hyla -y

The option `-y` will tell to rubyGems to deploy the gem but also the dependencies required.

*Note*: Due to usage of some new, not released yet Hyla features, you should install it from sources. Clone {hyla}[Hyla git repository] locally, move to Hyla directory and execute the following commands:  

   $ gem build hyla.gemspec
   $ sudo gem install hyla-1.0.x.gem -l

For detailed instructions how to install Hyla please refer this {hyla}/blob/master/README.adoc[README] file.

=== Generate the Slideshow

    $ hyla generate -c slideshow/_config.yaml
